python train.py \
    --model_name_or_path ckiplab/bert-base-chinese \
    --output_dir ./output/ckiplab-bert-base-chinese \
    --logging_steps 10 \
    --save_strategy steps \
    --data_seed 42 \
    --save_steps 100 \
    --save_total_limit 40 \
    --evaluation_strategy steps \
    --eval_steps 100 \
    --eval_dataset_size 500 \
    --max_train_samples 3000 \
    --max_eval_samples 500 \
    --per_device_eval_batch_size 1 \
    --max_new_tokens 32 \
    --dataloader_num_workers 8 \
    --group_by_length \
    --logging_strategy steps \
    --remove_unused_columns False \
    --do_train \
    --do_eval \
    --lora_r 64 \
    --lora_alpha 16 \
    --lora_modules all \
    --double_quant \
    --quant_type nf4 \
    --fp16 \
    --bits 4 \
    --warmup_ratio 0.03 \
    --lr_scheduler_type constant \
    --gradient_checkpointing \
    --dataset ./data \
    --dataset_format alpaca \
    --source_max_len 256 \
    --target_max_len 64 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 32 \
    --max_steps 1000 \
    --eval_steps 100 \
    --learning_rate 0.0002 \
    --adam_beta2 0.999 \
    --max_grad_norm 0.3 \
    --lora_dropout 0.05 \
    --weight_decay 0.0 \
    --seed 0
